export const FORMTYPES = {
  SET_FORM_DATA: 'SET_FORM_DATA', // Save user input
  CURRENT_FORM_STEP: 'CURRENT_FORM_STEP', // Set current form step number
  LOAD_START: 'LOAD_START',
  LOAD_COMPLETE: 'LOAD_COMPLETE',
};

export const RECOMMENDTYPES = {
  GET_RECOMMENDATIONS: 'GET_RECOMMENDATIONS',
  LOAD_START: 'LOAD_START',
  LOAD_COMPLETE: 'LOAD_COMPLETE',
};

export const ERRORTYPES = {
  ERROR_MSG: 'ERROR_MSG',
  RESET_ERROR: 'RESET_ERROR',
};
